word_list = [
    'abruptly',
    'absurd',
    'abyss',
    'affix',
    'aggravate',
    'askew',
    'avenue',
    'awkward',
    'axiom',
    'azure',
    'bagpipes',
    'buffalo',
    'banjo',
    'banyan',
    'bathrobe',
    'beige',
    'beleaguer',
    'bemused',
    'bergamot',
    'bewilder',
    'bibliophile',
    'blissful',
    'blunder',
    'blush',
    'boastful',
    'boggle',
    'bookworm',
    
    'calliope',
    'chiaroscurist',
    'chthonic',
    'clickbait',
    'coalesce',
    'coyly',
    
]